# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled1.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(385, 546)
        self.widget = QtWidgets.QWidget(Form)
        self.widget.setGeometry(QtCore.QRect(0, 0, 386, 548))
        self.widget.setObjectName("widget")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setGeometry(QtCore.QRect(20, 30, 361, 191))
        font = QtGui.QFont()
        font.setPointSize(65)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.pushButton_2 = QtWidgets.QPushButton(self.widget)
        self.pushButton_2.setGeometry(QtCore.QRect(110, 370, 161, 81))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_11 = QtWidgets.QPushButton(self.widget)
        self.pushButton_11.setGeometry(QtCore.QRect(110, 190, 161, 81))
        self.pushButton_11.setObjectName("pushButton_11")
        self.pushButton_14 = QtWidgets.QPushButton(self.widget)
        self.pushButton_14.setGeometry(QtCore.QRect(110, 280, 161, 81))
        self.pushButton_14.setObjectName("pushButton_14")
        self.widget_2 = QtWidgets.QWidget(Form)
        self.widget_2.setGeometry(QtCore.QRect(0, 0, 386, 548))
        self.widget_2.setObjectName("widget_2")
        self.label_2 = QtWidgets.QLabel(self.widget_2)
        self.label_2.setGeometry(QtCore.QRect(70, 10, 291, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_5 = QtWidgets.QLabel(self.widget_2)
        self.label_5.setGeometry(QtCore.QRect(10, 270, 331, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.widget_2)
        self.label_6.setGeometry(QtCore.QRect(0, 300, 301, 21))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.widget_2)
        self.label_7.setGeometry(QtCore.QRect(10, 450, 371, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.widget_2)
        self.label_8.setGeometry(QtCore.QRect(10, 470, 321, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.pushButton_12 = QtWidgets.QPushButton(self.widget_2)
        self.pushButton_12.setGeometry(QtCore.QRect(10, 10, 51, 51))
        self.pushButton_12.setStyleSheet("background-image: url(:/icons/icon/backup.png);")
        self.pushButton_12.setText("")
        self.pushButton_12.setObjectName("pushButton_12")
        self.label_12 = QtWidgets.QLabel(self.widget_2)
        self.label_12.setGeometry(QtCore.QRect(0, 320, 351, 21))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.label_13 = QtWidgets.QLabel(self.widget_2)
        self.label_13.setGeometry(QtCore.QRect(10, 500, 301, 21))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.label_3 = QtWidgets.QLabel(self.widget_2)
        self.label_3.setGeometry(QtCore.QRect(0, 110, 371, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.widget_2)
        self.label_4.setGeometry(QtCore.QRect(0, 140, 351, 21))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label_36 = QtWidgets.QLabel(self.widget_2)
        self.label_36.setGeometry(QtCore.QRect(0, 160, 381, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_36.setFont(font)
        self.label_36.setObjectName("label_36")
        self.widget_3 = QtWidgets.QWidget(Form)
        self.widget_3.setGeometry(QtCore.QRect(0, 0, 386, 151))
        self.widget_3.setObjectName("widget_3")
        self.label_9 = QtWidgets.QLabel(self.widget_3)
        self.label_9.setGeometry(QtCore.QRect(50, 30, 291, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.widget_3)
        self.label_10.setGeometry(QtCore.QRect(140, 60, 101, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.pushButton_3 = QtWidgets.QPushButton(self.widget_3)
        self.pushButton_3.setGeometry(QtCore.QRect(150, 80, 75, 41))
        self.pushButton_3.setObjectName("pushButton_3")
        self.label_11 = QtWidgets.QLabel(self.widget_3)
        self.label_11.setGeometry(QtCore.QRect(90, 120, 271, 20))
        self.label_11.setObjectName("label_11")
        self.widget_5 = QtWidgets.QWidget(Form)
        self.widget_5.setGeometry(QtCore.QRect(0, 0, 386, 548))
        self.widget_5.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.widget_5.setObjectName("widget_5")
        self.label_17 = QtWidgets.QLabel(self.widget_5)
        self.label_17.setGeometry(QtCore.QRect(40, 10, 341, 51))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_17.setFont(font)
        self.label_17.setObjectName("label_17")
        self.label_18 = QtWidgets.QLabel(self.widget_5)
        self.label_18.setGeometry(QtCore.QRect(20, 180, 341, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_18.setFont(font)
        self.label_18.setObjectName("label_18")
        self.label_19 = QtWidgets.QLabel(self.widget_5)
        self.label_19.setGeometry(QtCore.QRect(170, 250, 51, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_19.setFont(font)
        self.label_19.setObjectName("label_19")
        self.pushButton_5 = QtWidgets.QPushButton(self.widget_5)
        self.pushButton_5.setGeometry(QtCore.QRect(140, 320, 101, 61))
        self.pushButton_5.setObjectName("pushButton_5")
        self.label_20 = QtWidgets.QLabel(self.widget_5)
        self.label_20.setGeometry(QtCore.QRect(10, 380, 371, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_20.setFont(font)
        self.label_20.setObjectName("label_20")
        self.pushButton_8 = QtWidgets.QPushButton(self.widget_5)
        self.pushButton_8.setGeometry(QtCore.QRect(120, 450, 141, 71))
        self.pushButton_8.setObjectName("pushButton_8")
        self.label_28 = QtWidgets.QLabel(self.widget_5)
        self.label_28.setGeometry(QtCore.QRect(80, 70, 241, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_28.setFont(font)
        self.label_28.setObjectName("label_28")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.widget_5)
        self.lineEdit_3.setGeometry(QtCore.QRect(10, 120, 371, 20))
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.widget_6 = QtWidgets.QWidget(Form)
        self.widget_6.setGeometry(QtCore.QRect(0, 0, 386, 361))
        self.widget_6.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.widget_6.setObjectName("widget_6")
        self.label_14 = QtWidgets.QLabel(self.widget_6)
        self.label_14.setGeometry(QtCore.QRect(120, 10, 81, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_14.setFont(font)
        self.label_14.setObjectName("label_14")
        self.label_15 = QtWidgets.QLabel(self.widget_6)
        self.label_15.setGeometry(QtCore.QRect(210, 15, 41, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_15.setFont(font)
        self.label_15.setObjectName("label_15")
        self.label_16 = QtWidgets.QLabel(self.widget_6)
        self.label_16.setGeometry(QtCore.QRect(60, 60, 251, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_16.setFont(font)
        self.label_16.setObjectName("label_16")
        self.label_25 = QtWidgets.QLabel(self.widget_6)
        self.label_25.setGeometry(QtCore.QRect(80, 150, 251, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_25.setFont(font)
        self.label_25.setObjectName("label_25")
        self.pushButton_4 = QtWidgets.QPushButton(self.widget_6)
        self.pushButton_4.setGeometry(QtCore.QRect(130, 100, 91, 41))
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_7 = QtWidgets.QPushButton(self.widget_6)
        self.pushButton_7.setGeometry(QtCore.QRect(130, 190, 91, 41))
        self.pushButton_7.setObjectName("pushButton_7")
        self.label_26 = QtWidgets.QLabel(self.widget_6)
        self.label_26.setGeometry(QtCore.QRect(60, 250, 251, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_26.setFont(font)
        self.label_26.setObjectName("label_26")
        self.pushButton_9 = QtWidgets.QPushButton(self.widget_6)
        self.pushButton_9.setGeometry(QtCore.QRect(130, 300, 91, 41))
        self.pushButton_9.setObjectName("pushButton_9")
        self.widget_7 = QtWidgets.QWidget(Form)
        self.widget_7.setGeometry(QtCore.QRect(0, 0, 386, 371))
        self.widget_7.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.widget_7.setObjectName("widget_7")
        self.label_21 = QtWidgets.QLabel(self.widget_7)
        self.label_21.setGeometry(QtCore.QRect(50, 70, 301, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_21.setFont(font)
        self.label_21.setObjectName("label_21")
        self.label_22 = QtWidgets.QLabel(self.widget_7)
        self.label_22.setGeometry(QtCore.QRect(50, 110, 301, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_22.setFont(font)
        self.label_22.setObjectName("label_22")
        self.pushButton_6 = QtWidgets.QPushButton(self.widget_7)
        self.pushButton_6.setGeometry(QtCore.QRect(150, 172, 75, 61))
        self.pushButton_6.setObjectName("pushButton_6")
        self.label_29 = QtWidgets.QLabel(self.widget_7)
        self.label_29.setGeometry(QtCore.QRect(80, 250, 301, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_29.setFont(font)
        self.label_29.setObjectName("label_29")
        self.lineEdit_4 = QtWidgets.QLineEdit(self.widget_7)
        self.lineEdit_4.setGeometry(QtCore.QRect(10, 290, 371, 20))
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.pushButton_13 = QtWidgets.QPushButton(self.widget_7)
        self.pushButton_13.setGeometry(QtCore.QRect(150, 320, 75, 23))
        self.pushButton_13.setObjectName("pushButton_13")
        self.widget_4 = QtWidgets.QWidget(Form)
        self.widget_4.setGeometry(QtCore.QRect(0, 0, 386, 201))
        self.widget_4.setObjectName("widget_4")
        self.label_23 = QtWidgets.QLabel(self.widget_4)
        self.label_23.setGeometry(QtCore.QRect(110, 20, 361, 21))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_23.setFont(font)
        self.label_23.setObjectName("label_23")
        self.pushButton = QtWidgets.QPushButton(self.widget_4)
        self.pushButton.setEnabled(True)
        self.pushButton.setGeometry(QtCore.QRect(0, 60, 41, 41))
        self.pushButton.setCheckable(False)
        self.pushButton.setFlat(False)
        self.pushButton.setObjectName("pushButton")
        self.pushButton_15 = QtWidgets.QPushButton(self.widget_4)
        self.pushButton_15.setGeometry(QtCore.QRect(344, 60, 41, 41))
        self.pushButton_15.setObjectName("pushButton_15")
        self.tableWidget = QtWidgets.QTableWidget(self.widget_4)
        self.tableWidget.setGeometry(QtCore.QRect(45, 60, 291, 101))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(3)
        self.tableWidget.setRowCount(1)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(0, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(0, 2, item)
        self.pushButton_17 = QtWidgets.QPushButton(self.widget_4)
        self.pushButton_17.setGeometry(QtCore.QRect(0, 0, 51, 51))
        self.pushButton_17.setStyleSheet("background-image: url(:/icons/icon/backup.png);")
        self.pushButton_17.setText("")
        self.pushButton_17.setObjectName("pushButton_17")
        self.widget_8 = QtWidgets.QWidget(Form)
        self.widget_8.setGeometry(QtCore.QRect(0, 0, 386, 231))
        self.widget_8.setObjectName("widget_8")
        self.label_24 = QtWidgets.QLabel(self.widget_8)
        self.label_24.setGeometry(QtCore.QRect(80, 10, 241, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_24.setFont(font)
        self.label_24.setObjectName("label_24")
        self.lineEdit = QtWidgets.QLineEdit(self.widget_8)
        self.lineEdit.setGeometry(QtCore.QRect(10, 50, 371, 20))
        self.lineEdit.setObjectName("lineEdit")
        self.label_27 = QtWidgets.QLabel(self.widget_8)
        self.label_27.setGeometry(QtCore.QRect(110, 80, 251, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_27.setFont(font)
        self.label_27.setObjectName("label_27")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.widget_8)
        self.lineEdit_2.setGeometry(QtCore.QRect(10, 120, 371, 20))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.pushButton_16 = QtWidgets.QPushButton(self.widget_8)
        self.pushButton_16.setGeometry(QtCore.QRect(140, 150, 75, 51))
        self.pushButton_16.setObjectName("pushButton_16")
        self.widget_10 = QtWidgets.QWidget(Form)
        self.widget_10.setGeometry(QtCore.QRect(0, 0, 386, 261))
        self.widget_10.setObjectName("widget_10")
        self.label_30 = QtWidgets.QLabel(self.widget_10)
        self.label_30.setGeometry(QtCore.QRect(30, 30, 121, 41))
        font = QtGui.QFont()
        font.setPointSize(22)
        self.label_30.setFont(font)
        self.label_30.setObjectName("label_30")
        self.pushButton_10 = QtWidgets.QPushButton(self.widget_10)
        self.pushButton_10.setGeometry(QtCore.QRect(140, 210, 75, 41))
        self.pushButton_10.setObjectName("pushButton_10")
        self.label_31 = QtWidgets.QLabel(self.widget_10)
        self.label_31.setGeometry(QtCore.QRect(150, 30, 291, 41))
        font = QtGui.QFont()
        font.setPointSize(22)
        self.label_31.setFont(font)
        self.label_31.setObjectName("label_31")
        self.pushButton_21 = QtWidgets.QPushButton(self.widget_10)
        self.pushButton_21.setGeometry(QtCore.QRect(10, 100, 151, 51))
        self.pushButton_21.setObjectName("pushButton_21")
        self.pushButton_22 = QtWidgets.QPushButton(self.widget_10)
        self.pushButton_22.setGeometry(QtCore.QRect(220, 100, 151, 51))
        self.pushButton_22.setObjectName("pushButton_22")
        self.label_34 = QtWidgets.QLabel(self.widget_10)
        self.label_34.setGeometry(QtCore.QRect(10, 70, 131, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_34.setFont(font)
        self.label_34.setObjectName("label_34")
        self.label_35 = QtWidgets.QLabel(self.widget_10)
        self.label_35.setGeometry(QtCore.QRect(220, 70, 131, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_35.setFont(font)
        self.label_35.setObjectName("label_35")
        self.widget_9 = QtWidgets.QWidget(Form)
        self.widget_9.setGeometry(QtCore.QRect(0, 0, 386, 231))
        self.widget_9.setObjectName("widget_9")
        self.pushButton_18 = QtWidgets.QPushButton(self.widget_9)
        self.pushButton_18.setGeometry(QtCore.QRect(110, 60, 151, 51))
        self.pushButton_18.setObjectName("pushButton_18")
        self.pushButton_19 = QtWidgets.QPushButton(self.widget_9)
        self.pushButton_19.setGeometry(QtCore.QRect(110, 142, 151, 51))
        self.pushButton_19.setObjectName("pushButton_19")
        self.label_32 = QtWidgets.QLabel(self.widget_9)
        self.label_32.setGeometry(QtCore.QRect(80, 20, 251, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_32.setFont(font)
        self.label_32.setObjectName("label_32")
        self.widget_11 = QtWidgets.QWidget(Form)
        self.widget_11.setGeometry(QtCore.QRect(0, 0, 386, 191))
        self.widget_11.setObjectName("widget_11")
        self.label_33 = QtWidgets.QLabel(self.widget_11)
        self.label_33.setGeometry(QtCore.QRect(100, 10, 251, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_33.setFont(font)
        self.label_33.setObjectName("label_33")
        self.comboBox = QtWidgets.QComboBox(self.widget_11)
        self.comboBox.setGeometry(QtCore.QRect(40, 70, 301, 22))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.pushButton_20 = QtWidgets.QPushButton(self.widget_11)
        self.pushButton_20.setGeometry(QtCore.QRect(100, 110, 151, 51))
        self.pushButton_20.setObjectName("pushButton_20")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "АКЫЗУМ"))
        self.pushButton_2.setText(_translate("Form", "ПРАВИЛА"))
        self.pushButton_11.setText(_translate("Form", "ИГРА"))
        self.pushButton_14.setText(_translate("Form", "СТАТИСТИКА"))
        self.label_2.setText(_translate("Form", "Правила АКЫЗУМа"))
        self.label_5.setText(_translate("Form", "2. Второй слушает перевернутую"))
        self.label_6.setText(_translate("Form", " запись и пытыется повторить"))
        self.label_7.setText(_translate("Form", "3. В конце мы соединяем все части, "))
        self.label_8.setText(_translate("Form", "переворачиваем и второй игрок"))
        self.label_12.setText(_translate("Form", " фрагмен за фрагментом"))
        self.label_13.setText(_translate("Form", "пытается угадать песню"))
        self.label_3.setText(_translate("Form", "1. Сначала первый игрок записывает"))
        self.label_4.setText(_translate("Form", " песню втайне от второго игрока"))
        self.label_36.setText(_translate("Form", "(или выбирает в новогоднем режиме)"))
        self.label_9.setText(_translate("Form", "Как только будете готовы нажмите на кнопку ниже для записи"))
        self.label_10.setText(_translate("Form", "кнопку ниже"))
        self.pushButton_3.setText(_translate("Form", "СТАРТ!!!"))
        self.label_11.setText(_translate("Form", "ВАРНИНГ!!! У вас есть только 12 секунд!"))
        self.label_17.setText(_translate("Form", "Зовите второго игрока"))
        self.label_18.setText(_translate("Form", "Ниже вы можете прослушать запись первого"))
        self.label_19.setText(_translate("Form", "игрока"))
        self.pushButton_5.setText(_translate("Form", "ПРОСЛУШАТЬ!!!"))
        self.label_20.setText(_translate("Form", "Готов записать песню по частям? Жми на кнопку"))
        self.pushButton_8.setText(_translate("Form", "К ЗАПИСИ!!!"))
        self.label_28.setText(_translate("Form", "Введите свое имя, Игрок 2:"))
        self.lineEdit_3.setText(_translate("Form", "Игрок 1"))
        self.label_14.setText(_translate("Form", "часть:"))
        self.label_15.setText(_translate("Form", "1"))
        self.label_16.setText(_translate("Form", "Прослушать часть"))
        self.label_25.setText(_translate("Form", "Записать часть"))
        self.pushButton_4.setText(_translate("Form", "Прослушать"))
        self.pushButton_7.setText(_translate("Form", "Записать"))
        self.label_26.setText(_translate("Form", "Следующая часть"))
        self.pushButton_9.setText(_translate("Form", "Некст"))
        self.label_21.setText(_translate("Form", "Готовы прослушать результат и попытаться угадать песню?"))
        self.label_22.setText(_translate("Form", " и попытаться угадать песню?"))
        self.pushButton_6.setText(_translate("Form", "СЛУШАТЬ!!!"))
        self.label_29.setText(_translate("Form", "Впишите ответ ниже:"))
        self.lineEdit_4.setText(_translate("Form", "Название песни"))
        self.pushButton_13.setText(_translate("Form", "Готово"))
        self.label_23.setText(_translate("Form", "СТАТИСТИКА"))
        self.pushButton.setText(_translate("Form", "<"))
        self.pushButton_15.setText(_translate("Form", ">"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("Form", "1 Игрок"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("Form", "2 Игрок"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("Form", "Победил"))
        __sortingEnabled = self.tableWidget.isSortingEnabled()
        self.tableWidget.setSortingEnabled(False)
        item = self.tableWidget.item(0, 0)
        item.setText(_translate("Form", "п"))
        item = self.tableWidget.item(0, 1)
        item.setText(_translate("Form", "п"))
        item = self.tableWidget.item(0, 2)
        item.setText(_translate("Form", "п"))
        self.tableWidget.setSortingEnabled(__sortingEnabled)
        self.label_24.setText(_translate("Form", "Введите свое имя, Игрок 1:"))
        self.lineEdit.setText(_translate("Form", "Игрок 2"))
        self.label_27.setText(_translate("Form", "И название песни:"))
        self.lineEdit_2.setText(_translate("Form", "Песня"))
        self.pushButton_16.setText(_translate("Form", "Продолжить"))
        self.label_30.setText(_translate("Form", "Победил"))
        self.pushButton_10.setText(_translate("Form", "Домой"))
        self.label_31.setText(_translate("Form", "Игрок"))
        self.pushButton_21.setText(_translate("Form", "Проиграть"))
        self.pushButton_22.setText(_translate("Form", "Проиграть"))
        self.label_34.setText(_translate("Form", "Запись Игрока 1:"))
        self.label_35.setText(_translate("Form", "Запись Игрока 2:"))
        self.pushButton_18.setText(_translate("Form", "Оригинальная"))
        self.pushButton_19.setText(_translate("Form", "Новогодняя"))
        self.label_32.setText(_translate("Form", "Выберите режим игры:"))
        self.label_33.setText(_translate("Form", "Выберите песню:"))
        self.comboBox.setItemText(0, _translate("Form", "We wish you a merry christmas"))
        self.comboBox.setItemText(1, _translate("Form", "Jingle bells"))
        self.comboBox.setItemText(2, _translate("Form", "В лесу родилась ёлочка"))
        self.comboBox.setItemText(3, _translate("Form", "Три белых коня"))
        self.pushButton_20.setText(_translate("Form", "Дальше"))
import resourses_rc
